version: '3.8'
services:
  user-service:
    build:
      context: .
      target: development
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/usersqlserver
    volumes:
      - ./:/app
#    command: java -jar app.jar -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  mysql:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=user
    volumes:
      - user_data:/var/lib/mysql
      - user_config:/etc/mysql/conf.d
volumes:
  user_data:
  user_config: